name: Deploy to shinyapps.io
on:

  # run on any push 
  push:
  # run on request (via button in actions menu)
  workflow_dispatch:
      
jobs:
  deploy:
    name: Deploy to shinyapps
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
          use-public-rspm: true
      - name: Instal .NET
        run: |
          sudo apt install git
          sudo apt install nuget
          sudo nuget update -self
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt install libxml2-dev
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/5.18 main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install mono-complete
          wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install apt-transport-https
          sudo apt-get update
          sudo apt-get install dotnet-sdk-3.1
      - name: Install R packages
        run: |
          install.packages('pak')
          pak::pak("mitchelloharawild/icons")
          pak::pak("jespermaag/gganatogram")
          pak::pak("Open-Systems-Pharmacology/rClr")
          pak::pak("Open-Systems-Pharmacology/OSPSuite-R@v11.3.520")
          icons::download_health_icons()
        shell: Rscript {0} 
      - name: deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: demo-shiny-ospsuite
          accountName: pchelle

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
