name: Deploy to shinyapps.io
on:

  # run on any push 
  push:
  # run on request (via button in actions menu)
  workflow_dispatch:
      
jobs:
  deploy:
    name: Deploy to shinyapps
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
          use-public-rspm: true
      - name: Instal .NET
        run: |
          sudo apt-get install dotnet-runtime-8.0 libcurl4-openssl-dev libssl-dev libxml2-dev 
          sudo apt-get install libfontconfig1-dev libharfbuzz-dev libfribidi-dev
          sudo apt-get install libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
      - name: Install R packages
        run: |
          install.packages('pak')
          pak::pak("mitchelloharawild/icons")
          pak::pak("jespermaag/gganatogram")
          pak::pak("Open-Systems-Pharmacology/rClr")
          pak::pak("Open-Systems-Pharmacology/OSPSuite-R@v11.3.520")
          icons::download_health_icons()
        shell: Rscript {0} 
      - name: deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: demo-shiny-ospsuite
          accountName: pchelle

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
