name: Run App Locally

on:
  push

jobs:
  run-app:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.3.1'
          use-public-rspm: true
      - name: Install all R packages
        run: |
          install.packages(c('dplyr','purrr','covr','readr','tidyr','webshot','spelling','readxl','data.table','gridtext','ggtext','tidyselect','testthat','rmarkdown','pkgdown','openxlsx'))
          install.packages(c('shiny','shinydashboard','shinyWidgets','ggplot2', 'remotes'))
          remotes::install_github("mitchelloharawild/icons@v0.1.0")
          remotes::install_github("jespermaag/gganatogram")
          install.packages('https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v0.9.1/rClr_0.9.1.zip', repos = NULL, type = 'binary')
          download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip?pr=false', destfile = 'ospsuite.utils.zip', mode='wb')
          install.packages('ospsuite.utils.zip', repos = NULL, type = 'binary')
          unlink('ospsuite.utils.zip')
          download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip?pr=false', destfile = 'tlf.zip', mode='wb')
          install.packages('tlf.zip', repos = NULL, type = 'binary')
          unlink('tlf.zip')
          download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip?pr=false', destfile = 'ospsuite.zip', mode='wb')
          install.packages('ospsuite.zip', repos = NULL, type = 'binary')
          unlink('ospsuite.zip')
        shell: Rscript {0}
      - name: Run app
        run: |
          shiny::runApp()
        shell: Rscript {0}
        
